### ISSUE TITLE
Linux script: module 'dbus' has no attribute 'exceptions'

### ISSUE THREAD

**Issue by lquenti** [GEANT/CAT#211]
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [x] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [ ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

When starting the eduroam cat python script for linux, the following error occurs:

```
lquenti in ~/Downloads λ python3 eduroam-linux-Universitat_Gottingen-Universitat_Gottingen.py 
Dieses Installationsprogramm wurde für Universität Göttingen hergestellt.

Mehr Informationen und Kommentare:

EMAIL: campussupport@uni-goettingen.de
WWW: https://wiki.student.uni-goettingen.de/support/wlan

Das Installationsprogramm wurde mit Software vom GEANT Projekt erstellt.

-------
Dieses Installationsprogramm funktioniert nur für Anwender von Universität Göttingen in der Benutzergruppe: Universität Göttingen.

Weiter? (J/N) [J]J

-------
Directory /home/lquenti/.cat_installer exists; some of its files may be overwritten.

Weiter? (J/N) [J]J
Traceback (most recent call last):
  File "eduroam-linux-Universitat_Gottingen-Universitat_Gottingen.py", line 751, in connect_to_nm
    self.bus = dbus.SystemBus()
AttributeError: module 'dbus' has no attribute 'SystemBus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eduroam-linux-Universitat_Gottingen-Universitat_Gottingen.py", line 1061, in <module>
    run_installer()
  File "eduroam-linux-Universitat_Gottingen-Universitat_Gottingen.py", line 197, in run_installer
    if config_tool.connect_to_nm() is None:
  File "eduroam-linux-Universitat_Gottingen-Universitat_Gottingen.py", line 752, in connect_to_nm
    except dbus.exceptions.DBusException:
AttributeError: module 'dbus' has no attribute 'exceptions'
```

## How to reproduce issue

Run the script as shown above with the global python3 installation as described below.
 
## Detail of issue
I downloaded the script from [here](https://cat.eduroam.org/user/API.php?action=downloadInstaller&api_version=2&lang=de&device=linux&profile=6187)

My python version (the newest one in the arch repos):
```
python -V -V
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
```

All globally installed python packages:
```
lquenti in ~/Downloads λ pip3 freeze
anki==2.1.26
ankirspy==2.1.26
appdirs==1.4.4
aqt==2.1.26
arandr==0.1.10
attrs==20.2.0
beautifulsoup4==4.9.3
btrfsutil==1.2.0
CacheControl==0.12.6
cffi==1.14.3
chardet==3.0.4
colorama==0.4.4
contextlib2==0.6.0.post1
cryptography==3.2.1
decorator==4.4.2
distlib==0.3.1
distro==1.5.0
dnspython==2.0.0
greenlet==0.4.17
html5lib==1.1
icdiff==1.9.1
idna==2.10
importlib-metadata==2.0.0
isc==2.0
iso8601==0.1.13
jsonschema==3.2.0
lensfun==0.3.95
lit==0.10.1.dev0
Markdown==3.3
mpmath==1.1.0
msgpack==1.0.0
ordered-set==4.0.2
packaging==20.4
pep517==0.8.2
ply==3.11
progress==1.5
protobuf==3.12.4
psutil==5.7.2
pyasn1==0.4.8
PyAudio==0.2.11
pycairo==1.20.0
pycparser==2.20
PyGObject==3.38.0
pynvim==0.4.2
pyparsing==2.4.7
PyQt5==5.15.1
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.1
pyrsistent==0.17.3
pyte==0.8.0
requests==2.24.0
resolvelib==0.4.0
retrying==1.3.3
Send2Trash==1.5.0
six==1.15.0
soupsieve==2.0.1
sympy==1.6.2
team==1.0
thefuck==3.30
toml==0.10.1
urllib3==1.25.10
wcwidth==0.2.5
webencodings==0.5.1
youtube-dl==2020.9.20
zipp==3.4.0
```
dbus exists and is an buildin, as seen when
```
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus, inspect
>>> inspect.getsource(dbus)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/inspect.py", line 985, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python3.8/inspect.py", line 967, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.8/inspect.py", line 780, in findsource
    file = getsourcefile(object)
  File "/usr/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/usr/lib/python3.8/inspect.py", line 659, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'dbus' (namespace)> is a built-in module
```
It is true that neither `dbus.SystemBus` nor `dbus.exceptions` exist.

I'd love to send you the source code, but it's just a shared object since:
```
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> dbus.__path__
_NamespacePath(['/usr/lib/python3.8/site-packages/dbus', '/usr/lib/python3.8/site-packages/dbus'])
```
```
tree /usr/lib/python3.8/site-packages/dbus
/usr/lib/python3.8/site-packages/dbus
└── mainloop
    └── pyqt5.abi3.so

1 directory, 1 file
```

I'm quite confused about that. Please tell me if I can help further :)

**Comment by lquenti** [comment]
I fixed it by installing the arch package `python-dbus`.

This just leaves the question, why dbus still was includable... Is the empty package part of the core?

**Comment by lquenti** [comment]
for me it looks like pyqt5 creates a dummy dbus, which destroys the detection whether the package is installed.

I currently can't verify it.

**Comment by ikreb7** [comment]
Thanks for your very detailed error description. Could you say which distro and version do you use?

**Comment by lquenti** [comment]
Arch Linux, which is a rolling distribution with the newest packages. I'll try to further find a way to reproduce it today. I think I figured it out, I'll write a PR later

**Comment by lquenti** [comment]
How to properly reproduce it:

You need an arch installation with `python , `python-pyqt5` (which provides dbus) and __not__ `python-dbus`.

How to locally reproduce it:
```
# start a new docker with the latest archlinux, I fixed the version for debugging purposes
docker container run -it archlinux:20200908 /bin/bash
# 
# When inside the box, update the package repositories and install the needed packages
pacman -Syy && pacman -S --noconfirm python python-pyqt5
# 
# now when running python and importing dbus, the package exists, but is empty except for magic attributes
```

```
[root@93d936511110 /]# python3
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> dbus.exceptions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dbus' has no attribute 'exceptions'
```
